package enums;

public enum StatusEnum {
    SIGN_UP_SUCCESSFULLY,
    LOG_IN_SUCCESSFULLY,
    BOOK_RENTED_SUCCESSFULLY,
    REGISTER_SUCCESSFULLY,
    UPDATE_SUCCESSFULLY,
    DELETE_SUCCESSFULLY,
    CARRIED_SUCCESSFULLY
}
